info:
    description: "Inventory Management Service"
spring:
  application:
    name: inventory-service
  data:
    mongodb:
        uri: mongodb://localhost:27017/OMS
        database: OMS
security:
    basic:
      enabled: false

oms:
  appKey: inventory-service
  common:
    web:
      config:
        swagger:
          controllerPackage: com.oms.inventory.controller
          author: PVR
          apiName: Inventory-Service
          apiVersion: 1.0.0
          apiDescription: API for Inventory-service

logging:
??level:
????root: DEBUG
????org.springframework.web: ERROR
????com.oms.inventory: DEBUG

server:
    port: 9099


