spring:
  application:
    name: gateway-service 
server:
  port: 8765

      
security:
  basic:
    enabled: false


ribbon:
  eureka:
    enabled: true

zuul:
 prefix: /api
 ignoredPatterns: /api, /swagger-ui.html, /actuator/**, /configuration/**, /webjars/**, /swagger-resources/**, /swagger-composite/**, /v2/**, /jv/redirect/**, /heartbeat, /gateway/**, /favicon.ico, /public
 routes:
    first-service:
      path: /firstservice/**
      serviceId: venkatfirst
      #stripPrefix: false
    feign-service:
      path: /feignservice/**
      serviceId: venkatfeign
      #stripPrefix: false  

  #To ignore API-GATEWAY methods
 ignored-patterns: /hello

  # Prevent direct exposure of service-id from api-gateway
 ignored-services: '*'

  #if nothing is added that is called - dynamic routing      
    