info:
  description: "oms-security-service"

spring:
  application:
    name: oms-security-service



oms:
  appKey: customer-service
  common:
    web:
      config:
        swagger:
          controllerPackage: com.oms.customer.controller
          author: Panneerselvam
          apiName: oms-security-service
          apiVersion: 1.0.0resources
          apiDescription: API for Customer-service

security:
  basic:
    enabled: false
logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    com.oms.security: DEBUG
server:
  port: 9092
